spring.application.name=OnlineBookShop

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=BOOKSTORE_DATABASE;encrypt=false;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=123456
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Use 'none' - schema must be created by SQL script (avoids conflicts with identity/computed columns)
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect

# JWT Configuration
jwt.secret=OnlineBookShopSecretKeyForJWTAuthenticationMustBe256BitsLong!!
jwt.expiration=86400000
spring.web.resources.cache.cachecontrol.max-age=0
spring.web.resources.cache.cachecontrol.no-cache=true
spring.web.resources.cache.cachecontrol.no-store=true

# Mail Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=asasa2312003@gmail.com
spring.mail.password=vche ilrq wqhf twst
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
