spring.application.name=OnlineBookShop

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=OnlineBookShop;encrypt=false;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=123456
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Use 'none' - schema must be created by SQL script (avoids conflicts with identity/computed columns)
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect

# JWT Configuration
jwt.secret=OnlineBookShopSecretKeyForJWTAuthenticationMustBe256BitsLong!!
jwt.expiration=86400000
spring.web.resources.cache.cachecontrol.max-age=0
spring.web.resources.cache.cachecontrol.no-cache=true
spring.web.resources.cache.cachecontrol.no-store=true

# Cloudinary Configuration
cloudinary.cloud-name=du8cq6vfb
cloudinary.api-key=818536763593417
cloudinary.api-secret=jYUhbLzlA51aUU6-bepY7xCNLio

# File Upload
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB
