-- Patch existing order_items table if it was created without snapshot/payment columns.

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='order_items' AND COLUMN_NAME='book_id')
    ALTER TABLE order_items ADD book_id BIGINT NULL;

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='order_items' AND COLUMN_NAME='title_snapshot')
    ALTER TABLE order_items ADD title_snapshot NVARCHAR(255) NULL;

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='order_items' AND COLUMN_NAME='sku_snapshot')
    ALTER TABLE order_items ADD sku_snapshot NVARCHAR(80) NULL;

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='order_items' AND COLUMN_NAME='unit_price')
    ALTER TABLE order_items ADD unit_price DECIMAL(18,2) NULL;

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='order_items' AND COLUMN_NAME='line_total')
    ALTER TABLE order_items ADD line_total DECIMAL(18,2) NULL;

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='order_items' AND COLUMN_NAME='quantity')
    ALTER TABLE order_items ADD quantity INT NULL;

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='order_items' AND COLUMN_NAME='order_id')
    ALTER TABLE order_items ADD order_id BIGINT NULL;

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='order_items' AND COLUMN_NAME='variant_id')
    ALTER TABLE order_items ADD variant_id BIGINT NULL;

